import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("GPT-SoVITS is installed on demand through explicit helper scripts", async () => {
  const setupLauncher = await readFile(new URL("../setup-gpt-sovits.cmd", import.meta.url), "utf8");
  const startLauncher = await readFile(new URL("../start-gpt-sovits.cmd", import.meta.url), "utf8");
  const removeLauncher = await readFile(new URL("../remove-gpt-sovits.cmd", import.meta.url), "utf8");
  const setupScript = await readFile(new URL("../scripts/setup-gpt-sovits.ps1", import.meta.url), "utf8");
  const startScript = await readFile(new URL("../scripts/start-gpt-sovits.ps1", import.meta.url), "utf8");
  const removeScript = await readFile(new URL("../scripts/remove-gpt-sovits.ps1", import.meta.url), "utf8");
  const pathScript = await readFile(new URL("../scripts/agent-pet-paths.ps1", import.meta.url), "utf8");

  assert.match(setupLauncher, /setup-gpt-sovits\.ps1/);
  assert.match(setupLauncher, /%\*/);
  assert.match(startLauncher, /start-gpt-sovits\.ps1/);
  assert.match(removeLauncher, /remove-gpt-sovits\.ps1/);
  assert.match(setupScript, /micromamba-releases\/releases\/download\/\$MicromambaVersion\/micromamba-win-64\.exe/);
  assert.match(setupScript, /micromamba-win-64\.sha256/);
  assert.match(setupScript, /Get-FileHash -LiteralPath \$micromambaDownload -Algorithm SHA256/);
  assert.match(setupScript, /\[string\]\$MicromambaVersion = "2\.6\.2-1"/);
  assert.match(setupScript, /archive\/\$Version\.zip/);
  assert.match(setupScript, /\[string\]\$Version = "d523079fc05d9a8028d6085bffe4a2757c32abb6"/);
  assert.match(setupScript, /\.codex-source-revision/);
  assert.match(setupScript, /Replacing incomplete or outdated managed source/);
  assert.match(setupScript, /Type YES to continue/);
  assert.match(setupScript, /Resolve-AgentPetDataRoot -DataRoot \$DataRoot/);
  assert.match(pathScript, /AgentPet/);
  assert.match(pathScript, /CodexTaskCompanion/);
  assert.match(pathScript, /data-location\.json/);
  assert.match(setupScript, /\$env:MAMBA_ROOT_PREFIX/);
  assert.match(setupScript, /\$env:PIP_CONFIG_FILE = "NUL"/);
  assert.match(setupScript, /https:\/\/pypi\.tuna\.tsinghua\.edu\.cn\/simple/);
  assert.match(setupScript, /\$env:PIP_PROGRESS_BAR = "on"/);
  assert.match(setupScript, /function Enable-VisiblePipProgress/);
  assert.match(setupScript, /pip install --progress-bar on @Args/);
  assert.match(setupScript, /Reconfiguring PyTorch from \$previousDevice to \$Device/);
  assert.match(setupScript, /"-m", "pip", "uninstall", "--yes", "torch", "torchcodec"/);
  assert.match(setupScript, /\$env:PYTHONNOUSERSITE = "1"/);
  assert.match(setupScript, /"--no-rc", "create"/);
  assert.doesNotMatch(setupScript, /Get-Command (?:conda|git)\.exe/);
  assert.match(setupScript, /-File \$officialInstaller -Device \$Device -Source \$Source/);
  assert.match(startScript, /api_v2\.py/);
  assert.match(startScript, /\[int\]\$Port = 9880/);
  assert.match(startScript, /Join-Path \$environmentRoot "python\.exe"/);
  assert.doesNotMatch(startScript, /conda (?:activate|run)/i);
  assert.match(removeScript, /Type REMOVE to continue/);
  assert.match(removeScript, /StartsWith\(\$requiredPrefix, \[StringComparison\]::OrdinalIgnoreCase\)/);
  assert.match(removeScript, /Remove-Item -LiteralPath \$resolvedEngineRoot -Recurse -Force/);
});
